### ISSUE TITLE
Show request: Jane the Virgin

### ISSUE THREAD

**Issue by letschat6** [xdpirate/isitcutshort.com#39]
Please consider adding the show "Jane the  Virgin" to the site!

**Comment by xdpirate** [comment]
Hi there! Thanks for your contribution, but this show was not cancelled:

> Jane the Virgin wasn't canceled by its network. Instead, Urman made the creative decision to end the show at Season 5.

[Source](https://www.cbr.com/why-jane-the-virgin-ended/)

Have a look [here](https://github.com/xdpirate/isitcutshort.com#viable-show-inclusions) for information on which shows are viable to be included :)
