### ISSUE TITLE
Show suggestion: The Peripheral

### ISSUE THREAD

**Issue by grwthomps** [xdpirate/isitcutshort.com#44]
Read the "Viable show inclusions" in the readme before submitting:
https://github.com/xdpirate/isitcutshort.com#viable-show-inclusions

**Is this TV show viable for inclusion?** Yes

**Name of show:** The Peripheral

**IMDb link:** [IMDB](https://www.imdb.com/title/tt8291284/)

**Is it confirmed to be cancelled?** [Yes - according to Variety](https://variety.com/2023/tv/news/the-peripheral-canceled-amazon-season-2-renewal-1235700019/)

**Does it end on a cliffhanger?** [Not according to Reddit](https://old.reddit.com/r/ThePeripheral/comments/1781zxl/does_the_peripheral_have_an_ending/)

**Additional notes:**

**Comment by xdpirate** [comment]
Closing due to website shutdown. Thanks for your contribution.
