### ISSUE TITLE
Show request: orphan black

### ISSUE THREAD

**Issue by hearnia2k** [xdpirate/isitcutshort.com#7]
Please consider adding the show "orphan black" to the site!

**Comment by xdpirate** [comment]
>The showrunners of Orphan Black chose to end the show at five seasons, reportedly to ensure a satisfying ending rather than the abrupt cancelation that usually happens to cult shows.

https://www.giantfreakinrobot.com/ent/canceled-sci-fi-series-spinoff.html

Not cut short and doesn't end on a cliffhanger, see: https://github.com/xdpirate/isitcutshort.com#viable-show-inclusions
